name: Stats-Analysis CI
on: [ push, pull_request ]

jobs:
  mutation:
    name: PHP ${{ matrix.php }}-${{ matrix.os }} stats-analysis
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        php:
          - "8.0"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Psalm
        uses: docker://vimeo/psalm-github-actions
        env:
          REQUIRE_DEV: true
          CHECK_PLATFORM_REQUIREMENTS: false